// Code generated by MockGen. DO NOT EDIT.
// Source: ./providers/activities/activities_provider.go
//
// Generated by this command:
//
//	mockgen -source=./providers/activities/activities_provider.go -destination=./testing/mocks/providers/activities_provider_mock.go
//

// Package mock_activities_provider is a generated GoMock package.
package mock_providers

import (
	context "context"
	reflect "reflect"
	structures "type_writer_api/structures"

	gomock "go.uber.org/mock/gomock"
)

// MockActivitiesProviderInterface is a mock of ActivitiesProviderInterface interface.
type MockActivitiesProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockActivitiesProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockActivitiesProviderInterfaceMockRecorder is the mock recorder for MockActivitiesProviderInterface.
type MockActivitiesProviderInterfaceMockRecorder struct {
	mock *MockActivitiesProviderInterface
}

// NewMockActivitiesProviderInterface creates a new mock instance.
func NewMockActivitiesProviderInterface(ctrl *gomock.Controller) *MockActivitiesProviderInterface {
	mock := &MockActivitiesProviderInterface{ctrl: ctrl}
	mock.recorder = &MockActivitiesProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockActivitiesProviderInterface) EXPECT() *MockActivitiesProviderInterfaceMockRecorder {
	return m.recorder
}

// CreateActivity mocks base method.
func (m *MockActivitiesProviderInterface) CreateActivity(ctx context.Context, textInfo structures.Activity) (*structures.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivity", ctx, textInfo)
	ret0, _ := ret[0].(*structures.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivity indicates an expected call of CreateActivity.
func (mr *MockActivitiesProviderInterfaceMockRecorder) CreateActivity(ctx, textInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivity", reflect.TypeOf((*MockActivitiesProviderInterface)(nil).CreateActivity), ctx, textInfo)
}

// DeleteActivity mocks base method.
func (m *MockActivitiesProviderInterface) DeleteActivity(ctx context.Context, activityId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActivity", ctx, activityId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteActivity indicates an expected call of DeleteActivity.
func (mr *MockActivitiesProviderInterfaceMockRecorder) DeleteActivity(ctx, activityId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActivity", reflect.TypeOf((*MockActivitiesProviderInterface)(nil).DeleteActivity), ctx, activityId)
}

// GetActivities mocks base method.
func (m *MockActivitiesProviderInterface) GetActivities(ctx context.Context) ([]*structures.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivities", ctx)
	ret0, _ := ret[0].([]*structures.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivities indicates an expected call of GetActivities.
func (mr *MockActivitiesProviderInterfaceMockRecorder) GetActivities(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivities", reflect.TypeOf((*MockActivitiesProviderInterface)(nil).GetActivities), ctx)
}

// GetActivityByIdOrName mocks base method.
func (m *MockActivitiesProviderInterface) GetActivityByIdOrName(ctx context.Context, activityId *int, title *string) (*structures.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityByIdOrName", ctx, activityId, title)
	ret0, _ := ret[0].(*structures.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityByIdOrName indicates an expected call of GetActivityByIdOrName.
func (mr *MockActivitiesProviderInterfaceMockRecorder) GetActivityByIdOrName(ctx, activityId, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityByIdOrName", reflect.TypeOf((*MockActivitiesProviderInterface)(nil).GetActivityByIdOrName), ctx, activityId, title)
}

// UpdateActivity mocks base method.
func (m *MockActivitiesProviderInterface) UpdateActivity(ctx context.Context, updatedtextInfo structures.Activity) (*structures.Activity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivity", ctx, updatedtextInfo)
	ret0, _ := ret[0].(*structures.Activity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActivity indicates an expected call of UpdateActivity.
func (mr *MockActivitiesProviderInterfaceMockRecorder) UpdateActivity(ctx, updatedtextInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivity", reflect.TypeOf((*MockActivitiesProviderInterface)(nil).UpdateActivity), ctx, updatedtextInfo)
}
