// Code generated by MockGen. DO NOT EDIT.
// Source: ./providers/scores/scores_provider.go
//
// Generated by this command:
//
//	mockgen -source=./providers/scores/scores_provider.go -destination=./testing/mocks/providers/scores_provider_mock.go
//

// Package mock_scores_provider is a generated GoMock package.
package mock_providers

import (
	context "context"
	reflect "reflect"
	structures "type_writer_api/structures"

	gomock "go.uber.org/mock/gomock"
)

// MockScoresProviderInterface is a mock of ScoresProviderInterface interface.
type MockScoresProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockScoresProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockScoresProviderInterfaceMockRecorder is the mock recorder for MockScoresProviderInterface.
type MockScoresProviderInterfaceMockRecorder struct {
	mock *MockScoresProviderInterface
}

// NewMockScoresProviderInterface creates a new mock instance.
func NewMockScoresProviderInterface(ctrl *gomock.Controller) *MockScoresProviderInterface {
	mock := &MockScoresProviderInterface{ctrl: ctrl}
	mock.recorder = &MockScoresProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoresProviderInterface) EXPECT() *MockScoresProviderInterfaceMockRecorder {
	return m.recorder
}

// CreateScore mocks base method.
func (m *MockScoresProviderInterface) CreateScore(ctx context.Context, scoreInfo structures.Score) (*structures.Score, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateScore", ctx, scoreInfo)
	ret0, _ := ret[0].(*structures.Score)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateScore indicates an expected call of CreateScore.
func (mr *MockScoresProviderInterfaceMockRecorder) CreateScore(ctx, scoreInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateScore", reflect.TypeOf((*MockScoresProviderInterface)(nil).CreateScore), ctx, scoreInfo)
}

// DeleteScore mocks base method.
func (m *MockScoresProviderInterface) DeleteScore(ctx context.Context, scoreId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteScore", ctx, scoreId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteScore indicates an expected call of DeleteScore.
func (mr *MockScoresProviderInterfaceMockRecorder) DeleteScore(ctx, scoreId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteScore", reflect.TypeOf((*MockScoresProviderInterface)(nil).DeleteScore), ctx, scoreId)
}

// GetScoreById mocks base method.
func (m *MockScoresProviderInterface) GetScoreById(ctx context.Context, scoreId int) (*structures.Score, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScoreById", ctx, scoreId)
	ret0, _ := ret[0].(*structures.Score)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScoreById indicates an expected call of GetScoreById.
func (mr *MockScoresProviderInterfaceMockRecorder) GetScoreById(ctx, scoreId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScoreById", reflect.TypeOf((*MockScoresProviderInterface)(nil).GetScoreById), ctx, scoreId)
}

// GetScores mocks base method.
func (m *MockScoresProviderInterface) GetScores(ctx context.Context) ([]*structures.Score, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScores", ctx)
	ret0, _ := ret[0].([]*structures.Score)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetScores indicates an expected call of GetScores.
func (mr *MockScoresProviderInterfaceMockRecorder) GetScores(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScores", reflect.TypeOf((*MockScoresProviderInterface)(nil).GetScores), ctx)
}

// UpdateScore mocks base method.
func (m *MockScoresProviderInterface) UpdateScore(ctx context.Context, updatedtextInfo structures.Score) (*structures.Score, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, updatedtextInfo)
	ret0, _ := ret[0].(*structures.Score)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockScoresProviderInterfaceMockRecorder) UpdateScore(ctx, updatedtextInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockScoresProviderInterface)(nil).UpdateScore), ctx, updatedtextInfo)
}
