// Code generated by MockGen. DO NOT EDIT.
// Source: ./providers/texts/texts_provider.go
//
// Generated by this command:
//
//	mockgen -source=./providers/texts/texts_provider.go -destination=./testing/mocks/providers/texts_provider_mock.go -package=mock_providers
//

// Package mock_providers is a generated GoMock package.
package mock_providers

import (
	context "context"
	reflect "reflect"
	structures "type_writer_api/structures"

	gomock "go.uber.org/mock/gomock"
)

// MockTextsProviderInterface is a mock of TextsProviderInterface interface.
type MockTextsProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTextsProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockTextsProviderInterfaceMockRecorder is the mock recorder for MockTextsProviderInterface.
type MockTextsProviderInterfaceMockRecorder struct {
	mock *MockTextsProviderInterface
}

// NewMockTextsProviderInterface creates a new mock instance.
func NewMockTextsProviderInterface(ctrl *gomock.Controller) *MockTextsProviderInterface {
	mock := &MockTextsProviderInterface{ctrl: ctrl}
	mock.recorder = &MockTextsProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextsProviderInterface) EXPECT() *MockTextsProviderInterfaceMockRecorder {
	return m.recorder
}

// CreateText mocks base method.
func (m *MockTextsProviderInterface) CreateText(ctx context.Context, textInfo structures.Text) (*structures.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateText", ctx, textInfo)
	ret0, _ := ret[0].(*structures.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateText indicates an expected call of CreateText.
func (mr *MockTextsProviderInterfaceMockRecorder) CreateText(ctx, textInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateText", reflect.TypeOf((*MockTextsProviderInterface)(nil).CreateText), ctx, textInfo)
}

// DeleteText mocks base method.
func (m *MockTextsProviderInterface) DeleteText(ctx context.Context, textId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteText", ctx, textId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteText indicates an expected call of DeleteText.
func (mr *MockTextsProviderInterfaceMockRecorder) DeleteText(ctx, textId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteText", reflect.TypeOf((*MockTextsProviderInterface)(nil).DeleteText), ctx, textId)
}

// GetTextByIdOrTitle mocks base method.
func (m *MockTextsProviderInterface) GetTextByIdOrTitle(ctx context.Context, textId *int, title *string) (*structures.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTextByIdOrTitle", ctx, textId, title)
	ret0, _ := ret[0].(*structures.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTextByIdOrTitle indicates an expected call of GetTextByIdOrTitle.
func (mr *MockTextsProviderInterfaceMockRecorder) GetTextByIdOrTitle(ctx, textId, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTextByIdOrTitle", reflect.TypeOf((*MockTextsProviderInterface)(nil).GetTextByIdOrTitle), ctx, textId, title)
}

// GetTexts mocks base method.
func (m *MockTextsProviderInterface) GetTexts(ctx context.Context) ([]*structures.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTexts", ctx)
	ret0, _ := ret[0].([]*structures.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTexts indicates an expected call of GetTexts.
func (mr *MockTextsProviderInterfaceMockRecorder) GetTexts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTexts", reflect.TypeOf((*MockTextsProviderInterface)(nil).GetTexts), ctx)
}

// UpdateText mocks base method.
func (m *MockTextsProviderInterface) UpdateText(ctx context.Context, updatedtextInfo structures.Text) (*structures.Text, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateText", ctx, updatedtextInfo)
	ret0, _ := ret[0].(*structures.Text)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateText indicates an expected call of UpdateText.
func (mr *MockTextsProviderInterfaceMockRecorder) UpdateText(ctx, updatedtextInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateText", reflect.TypeOf((*MockTextsProviderInterface)(nil).UpdateText), ctx, updatedtextInfo)
}
