// Code generated by MockGen. DO NOT EDIT.
// Source: ./providers/users/users_provider.go
//
// Generated by this command:
//
//	mockgen -package=mock_providers -source=./providers/users/users_provider.go -destination=./testing/mocks/providers/users_provider_mock.go
//

// Package mock_providers is a generated GoMock package.
package mock_providers

import (
	context "context"
	reflect "reflect"
	structures "type_writer_api/structures"

	gomock "go.uber.org/mock/gomock"
)

// MockUsersProviderInterface is a mock of UsersProviderInterface interface.
type MockUsersProviderInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUsersProviderInterfaceMockRecorder
	isgomock struct{}
}

// MockUsersProviderInterfaceMockRecorder is the mock recorder for MockUsersProviderInterface.
type MockUsersProviderInterfaceMockRecorder struct {
	mock *MockUsersProviderInterface
}

// NewMockUsersProviderInterface creates a new mock instance.
func NewMockUsersProviderInterface(ctrl *gomock.Controller) *MockUsersProviderInterface {
	mock := &MockUsersProviderInterface{ctrl: ctrl}
	mock.recorder = &MockUsersProviderInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersProviderInterface) EXPECT() *MockUsersProviderInterfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUsersProviderInterface) CreateUser(ctx context.Context, userInfo structures.User) (*structures.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userInfo)
	ret0, _ := ret[0].(*structures.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUsersProviderInterfaceMockRecorder) CreateUser(ctx, userInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUsersProviderInterface)(nil).CreateUser), ctx, userInfo)
}

// DeleteUser mocks base method.
func (m *MockUsersProviderInterface) DeleteUser(ctx context.Context, userId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, userId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockUsersProviderInterfaceMockRecorder) DeleteUser(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockUsersProviderInterface)(nil).DeleteUser), ctx, userId)
}

// GetUserByIdOrUsername mocks base method.
func (m *MockUsersProviderInterface) GetUserByIdOrUsername(ctx context.Context, userId *int, username *string) (*structures.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByIdOrUsername", ctx, userId, username)
	ret0, _ := ret[0].(*structures.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByIdOrUsername indicates an expected call of GetUserByIdOrUsername.
func (mr *MockUsersProviderInterfaceMockRecorder) GetUserByIdOrUsername(ctx, userId, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByIdOrUsername", reflect.TypeOf((*MockUsersProviderInterface)(nil).GetUserByIdOrUsername), ctx, userId, username)
}

// GetUsers mocks base method.
func (m *MockUsersProviderInterface) GetUsers(ctx context.Context) ([]*structures.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", ctx)
	ret0, _ := ret[0].([]*structures.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockUsersProviderInterfaceMockRecorder) GetUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockUsersProviderInterface)(nil).GetUsers), ctx)
}

// UpdateUser mocks base method.
func (m *MockUsersProviderInterface) UpdateUser(ctx context.Context, updatedUserInfo structures.User) (*structures.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, updatedUserInfo)
	ret0, _ := ret[0].(*structures.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUsersProviderInterfaceMockRecorder) UpdateUser(ctx, updatedUserInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUsersProviderInterface)(nil).UpdateUser), ctx, updatedUserInfo)
}
